development:
  adapter: postgresql
  encoding: unicode
  database: chinaflash_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chinaflash_test
  pool: 5
  username:
  password:
